server:
  port: 80
  servlet:
    context-path: /wx-mp

openapi:
  key: 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

spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000
wx:
  mp:
    app-id: wx081aecf65e042273
    secret: 86ae29528218bf738ed7a8b3505ed68e
    token: sadtrain
    aes-key: SPgrgrG01GKu5D5kYW3bxy0ylJo5sczcYi0rL3elAyT

chatgpt:
  token: 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
  proxy-host: 127.0.0.1
  proxy-port: 80
  session-expiration-time: 30